Repository hassio-addons/addon-thelounge, pull requests merged in 2021-02, with the labels that each got.

#20 Upgrade add-on base image to 9.1.2
  thelounge/Dockerfile
  thelounge/build.json
Labels: dependencies, minor

#12 Add build dependencies for sqlite3
  thelounge/Dockerfile
Labels: bugfix

#29 :arrow_up: Upgrades nodejs to 14.15.5-r0
  thelounge/Dockerfile
Labels: dependencies
