Repository hassio-addons/addon-thelounge, pull requests merged in 2022-07, with the labels that each got.

#118 ⬆️ Upgrades nginx to 1.22.0-r1
  thelounge/Dockerfile
Labels: dependencies

#117 Link `python3` to `python` for the `sqlite3` JS module build
  thelounge/Dockerfile
Labels: bugfix

#119 ⬆️ Upgrades add-on base image to 12.2.0
  thelounge/Dockerfile
  thelounge/build.yaml
Labels: dependencies

#121 ⬆️ Upgrades add-on base image to 12.2.1
  thelounge/Dockerfile
  thelounge/build.yaml
Labels: dependencies

#120 Allow non-admins to access the add-on
  thelounge/config.yaml
Labels: new-feature
